{
    "name": "Odoo School",
    "version": "1.0.0",
    "sequence": -1000,
    "summary": "School Management System",
    "description": "Manage students, classes, subjects, fees and marks.",
    "category": "Education",
    "author": "Madhuvan Jain",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/school_groups.xml",
        "security/school_record_rules.xml",
        "security/ir.model.access.csv",
        "views/student_views.xml",
        "views/school_class_views.xml",
        "views/subject_views.xml",
        "views/fee_views.xml",
        "views/student_marks_entry_views.xml",
        "views/student_marks_views.xml",
        "views/marks_report_wizard_views.xml",
        "views/class_history_view.xml",
        "reports/marks_report_templates.xml",
        "reports/marks_report.xml",
        "views/marks_different_report_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
