{
    'name': 'hospital management',
    'version': '1.0.0',
    'sequence': '-100',
    'category': 'Hospital management ',
    'author': 'Madhuvan Jain',
    'summary': 'Hospital management system',
    'description': """It is a module that is use for hospital management/n""",
    'depends': ['mail'],
    'data': [
        "security/hospital_groups.xml",
        "security/hospital_record_rules.xml",
        "security/ir.model.access.csv",
        "views/patient_views.xml",
        "views/female_patient_views.xml",
        "views/appointment_views.xml",
        "views/doctor_view.xml",
        "views/guardian_view.xml",
        "views/patient_insurance_views.xml",
        "views/menu.xml",
        "views/Sequence.xml",
        "views/learn_action.xml",
        "views/email_templates.xml",
        "views/hospital_dashboard.xml",
        "views/report_paperformat.xml",
        "views/report_appointment.xml",
        "views/update_automatically_appointment_status.xml",
        "views/kanban_view_patient.xml", ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'assets': {},
    'license': 'LGPL-3',
}
